swagger: "2.0"
info:
  description: This is a test of a very boilerplate API Gateway
  version: 0.0.1
  title: Cognito Lambda GO
host: localhost:3000
schemes:
- http
- https
paths:
  /:
    get:
      tags:
      - boilerplate
      summary: Returns a basic message after authenticating
      description: ""
      operationId: boilerplate
      responses:
        200:
          description: "I hear you"
          schema:
            $ref: "#/definitions/Result"
        403:
          description: "I choose not to hear you"
          schema:
            $ref: "#/definitions/Error"
securityDefinitions:
  api_key:
    type: apiKey
    name: cognito_auth
    in: header
definitions:
  Result:
    type: object
    properties:
      structure:
        type: string
        description: This is only here to prove it's not the same as an error return
      message:
        type: string
        description: Mostly filler
  Error:
    type: object
    description: What happens when we get to the wrong place, or we aren't authenticated
    properties:
      message:
        type: string
        description: This error message can be misleading from AWS.  Often a failure to authenticate is shown when it's a 404.